const http=require('http');
const fs=require('fs'); const path=require('path'); const {spawnSync}=require('child_process'); const crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DATA=path.join(ROOT,'data'), UPLOADS=path.join(ROOT,'uploads');
fs.mkdirSync(DATA,{recursive:true}); fs.mkdirSync(UPLOADS,{recursive:true});
const db=new DatabaseSync(path.join(DATA,'theplug.sqlite'));
function sql(s){db.exec(s)}
sql(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS brands(id INTEGER PRIMARY KEY,name TEXT UNIQUE,slug TEXT UNIQUE,active INTEGER DEFAULT 1,logo_url TEXT,website TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE,slug TEXT UNIQUE,parent_id INTEGER,active INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,brand_id INTEGER,brand_name TEXT,mfg_part_id TEXT,the_plug_id TEXT,title TEXT,short_description TEXT,description TEXT,msrp_usd REAL,price_usd REAL,msrp_sar REAL,price_sar REAL,cost_sar REAL,category TEXT DEFAULT 'Performance',status TEXT DEFAULT 'active',stock INTEGER DEFAULT 0,low_stock_threshold INTEGER DEFAULT 3,lead_time TEXT,weight_kg REAL,seo_title TEXT,seo_description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,group_key TEXT UNIQUE,FOREIGN KEY(brand_id) REFERENCES brands(id));
CREATE TABLE IF NOT EXISTS product_aliases(id INTEGER PRIMARY KEY,product_id INTEGER,the_plug_id TEXT UNIQUE,source_sheet TEXT,source_row INTEGER,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS product_images(id INTEGER PRIMARY KEY,product_id INTEGER,url TEXT,alt_text TEXT,sort_order INTEGER,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS fitments(id INTEGER PRIMARY KEY,product_id INTEGER,car_brand TEXT,model TEXT,year_from INTEGER,year_to INTEGER,year_raw TEXT,chassis TEXT,liters TEXT,cylinders TEXT,engine TEXT,trim TEXT,notes TEXT,source_sheet TEXT,source_row INTEGER,UNIQUE(product_id,car_brand,model,year_raw,chassis,engine),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,order_no TEXT UNIQUE,customer_name TEXT,email TEXT,total REAL,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY,order_id INTEGER,product_id INTEGER,title TEXT,qty INTEGER,price REAL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY,first_name TEXT,last_name TEXT,email TEXT UNIQUE,phone TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT DEFAULT 'active');
CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY,product_id INTEGER,customer_name TEXT,rating INTEGER,body TEXT,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS coupons(id INTEGER PRIMARY KEY,code TEXT UNIQUE,type TEXT DEFAULT 'percent',amount REAL DEFAULT 0,active INTEGER DEFAULT 1,starts_at TEXT,ends_at TEXT);
CREATE TABLE IF NOT EXISTS pages(id INTEGER PRIMARY KEY,slug TEXT UNIQUE,title TEXT,body TEXT,status TEXT DEFAULT 'published',updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS content_blocks(id INTEGER PRIMARY KEY,key TEXT UNIQUE,label TEXT,value TEXT,type TEXT DEFAULT 'text',updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
CREATE TABLE IF NOT EXISTS inventory_logs(id INTEGER PRIMARY KEY,product_id INTEGER,delta INTEGER,reason TEXT,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS imports(id INTEGER PRIMARY KEY,filename TEXT,mode TEXT,rows_total INTEGER,products_created INTEGER,products_updated INTEGER,fitments_created INTEGER,issues INTEGER,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY,entity_type TEXT,entity_id INTEGER,action TEXT,summary TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
`);
function ensureColumn(table,col,def){try{db.exec(`ALTER TABLE ${table} ADD COLUMN ${col} ${def}`)}catch(e){if(!String(e.message).includes('duplicate column')) throw e}}
ensureColumn('brands','logo_url','TEXT'); ensureColumn('brands','website','TEXT'); ensureColumn('brands','notes','TEXT');
for(const [c,d] of [['short_description','TEXT'],['cost_sar','REAL'],['low_stock_threshold','INTEGER DEFAULT 3'],['lead_time','TEXT'],['weight_kg','REAL'],['seo_title','TEXT'],['seo_description','TEXT']]) ensureColumn('products',c,d);
ensureColumn('product_images','alt_text','TEXT'); ensureColumn('fitments','trim','TEXT'); ensureColumn('fitments','notes','TEXT');
function norm(s){return String(s??'').trim().replace(/\s+/g,' ')}
function slug(s){return norm(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function money(v){const m=String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/); return m?Number(m[0]):null}
function years(raw){let s=norm(raw).replace(/[–—]/g,'-'); if(!s)return [null,null]; let p=s.match(/(\d{4})\s*\+/);if(p)return [+p[1],null]; p=s.match(/(\d{4})\s*-\s*(\d{4})/);if(p)return [+p[1],+p[2]]; p=s.match(/\d{4}/);return p?[+p[0],+p[0]]:[null,null]}
function canonicalBrand(s){let x=norm(s); if(!x)return ''; const l=x.toLowerCase(); if(l==='p3'||l==='p3 gauges')return 'P3'; if(l==='valvetronic')return 'Valvetronic'; if(l==='autoid')return 'AUTOID'; return x.replace(/\b\w/g,c=>c.toUpperCase())}
function groupKey(r){const brand=canonicalBrand(r['Brand']||r.__sheet); const mfg=norm(r['MFG Part ID']); if(mfg&&mfg!=='_'&&mfg!=='-')return slug(brand)+'|mfg|'+mfg.toLowerCase(); const title=norm(r['Product Name']); const price=money(r['The Pluge Price SAR']||r['The Plug Price SAR']); const img=norm(r['Image 1 URL']); return slug(brand)+'|fallback|'+slug(title)+'|'+(price??'')+'|'+crypto.createHash('sha1').update(img).digest('hex').slice(0,8)}
function audit(type,id,action,summary){db.prepare('INSERT INTO audit_log(entity_type,entity_id,action,summary) VALUES(?,?,?,?)').run(type,id,action,summary||'')}
function getOrBrand(name){name=canonicalBrand(name)||'Unbranded'; const found=db.prepare('SELECT id FROM brands WHERE name=?').get(name);if(found)return found.id;return db.prepare('INSERT INTO brands(name,slug) VALUES(?,?)').run(name,slug(name)).lastInsertRowid}
function importRows(rows,mode='update'){
 let stats={rows_total:rows.length,products_created:0,products_updated:0,fitments_created:0,issues:0}; const seenImg=new Set(), updatedProducts=new Set();
 db.exec('BEGIN'); try{
  for(const r of rows){
   const title=norm(r['Product Name']); const brand=canonicalBrand(r['Brand']||r.__sheet); if(!title||!brand){stats.issues++;continue}
   const g=groupKey(r); let p=db.prepare('SELECT * FROM products WHERE group_key=?').get(g); const bid=getOrBrand(brand);
   const mfg=norm(r['MFG Part ID']); const tpid=norm(r['The Plug Part ID']); const desc=norm(r['Product Description']);
   const vals=[bid,brand,mfg,tpid,title,desc,money(r['MAP (MSRP) USD ']),money(r['The Pluge Price USD']||r['The Plug Price USD']),money(r['MAP (MSRP) SAR']),money(r['The Pluge Price SAR']||r['The Plug Price SAR'])];
   if(!p){const res=db.prepare(`INSERT INTO products(brand_id,brand_name,mfg_part_id,the_plug_id,title,description,msrp_usd,price_usd,msrp_sar,price_sar,group_key) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(...vals,g); p={id:res.lastInsertRowid};stats.products_created++;}
   else if(mode!=='add'){db.prepare(`UPDATE products SET brand_id=?,brand_name=?,mfg_part_id=?,the_plug_id=COALESCE(NULLIF(?,''),the_plug_id),title=?,description=?,msrp_usd=?,price_usd=?,msrp_sar=?,price_sar=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...vals,p.id);updatedProducts.add(p.id)}
   if(tpid)db.prepare('INSERT OR IGNORE INTO product_aliases(product_id,the_plug_id,source_sheet,source_row) VALUES(?,?,?,?)').run(p.id,tpid,r.__sheet,r.__row);
   if(!seenImg.has(p.id)){for(let i=1;i<=6;i++){const u=norm(r[`Image ${i} URL`]);if(u)db.prepare('INSERT OR IGNORE INTO product_images(product_id,url,alt_text,sort_order) VALUES(?,?,?,?)').run(p.id,u,title,i)} seenImg.add(p.id)}
   const [yf,yt]=years(r['Year of manufacture']); const fr=db.prepare(`INSERT OR IGNORE INTO fitments(product_id,car_brand,model,year_from,year_to,year_raw,chassis,liters,cylinders,engine,source_sheet,source_row) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(p.id,canonicalBrand(r['Car Brand']),norm(r['Model']),yf,yt,norm(r['Year of manufacture']),norm(r['Chasis']),norm(r['Liters']),norm(r['Cylinders']),norm(r['Engine']),r.__sheet,r.__row); if(fr.changes)stats.fitments_created++;
  }
  stats.products_updated=updatedProducts.size; db.exec('COMMIT'); return stats;
 }catch(e){db.exec('ROLLBACK');throw e}
}
function parseXlsx(file){const p=spawnSync('python',[path.join(ROOT,'tools','xlsx_parser.py'),file],{encoding:'utf8',maxBuffer:120*1024*1024});if(p.status!==0)throw new Error(p.stderr||'XLSX parse failed');return JSON.parse(p.stdout)}
function seedDefaults(){
 const defaults={store_name:'The Plug',domain:'theplug.inc',currency:'SAR',support_email:'customerservice@theplug.inc',shipping_threshold:'1400',hero_headline:'Performance Perfected For Your Drive.',hero_subheading:'Premium aftermarket parts to enhance your car’s performance, style, and reliability.',vin_provider:'API Ninjas',payment_gateway:'HyperPay'};
 for(const [k,v] of Object.entries(defaults))db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v);
 for(const c of ['Performance','Exterior','Interior','Wheels & Tires','Brakes & Suspension','Audio & Electronics','Lighting','Automotive Tools'])db.prepare('INSERT OR IGNORE INTO categories(name,slug) VALUES(?,?)').run(c,slug(c));
}
seedDefaults();
function json(res,obj,status=200){const b=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json','content-length':Buffer.byteLength(b)});res.end(b)}
function body(req){return new Promise((resolve,reject)=>{let a=[];req.on('data',c=>a.push(c));req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
function parseMultipart(buf,ct){const m=ct.match(/boundary=(.+)$/);if(!m)return null;const boundary='--'+m[1];const text=buf.toString('binary');const start=text.indexOf(boundary);const headEnd=text.indexOf('\r\n\r\n',start);const headers=text.slice(start,headEnd);const name=(headers.match(/filename="([^"]+)"/)||[])[1]||'upload.xlsx';const dataStart=headEnd+4;const end=text.indexOf('\r\n'+boundary,dataStart);return {name,data:buf.subarray(Buffer.byteLength(text.slice(0,dataStart),'binary'),Buffer.byteLength(text.slice(0,end),'binary'))}}
function mime(f){const e=path.extname(f).toLowerCase();return {'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp','.csv':'text/csv'}[e]||'application/octet-stream'}
function staticFile(res,file){if(!fs.existsSync(file)||!fs.statSync(file).isFile())return false;res.writeHead(200,{'content-type':mime(file)});fs.createReadStream(file).pipe(res);return true}
async function readJson(req){try{return JSON.parse((await body(req)).toString()||'{}')}catch{return {}}}
async function api(req,res,u){
 const method=req.method;
 if(u.pathname==='/api/products'&&method==='GET'){const q=norm(u.searchParams.get('q'));const brand=norm(u.searchParams.get('brand'));const category=norm(u.searchParams.get('category'));const limit=Math.min(200,Number(u.searchParams.get('limit')||24));let where=["p.status='active'"],args=[];if(q){where.push('(p.title LIKE ? OR p.mfg_part_id LIKE ? OR p.the_plug_id LIKE ?)');args.push('%'+q+'%','%'+q+'%','%'+q+'%')}if(brand){where.push('p.brand_name=?');args.push(brand)}if(category){where.push('p.category=?');args.push(category)}args.push(limit);return json(res,db.prepare(`SELECT p.*,(SELECT url FROM product_images i WHERE i.product_id=p.id ORDER BY sort_order LIMIT 1) image,(SELECT count(*) FROM fitments f WHERE f.product_id=p.id) fitment_count FROM products p WHERE ${where.join(' AND ')} ORDER BY p.updated_at DESC LIMIT ?`).all(...args))}
 if(u.pathname.match(/^\/api\/products\/\d+$/)&&method==='GET'){const id=+u.pathname.split('/').pop();const p=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!p)return json(res,{error:'Not found'},404);p.images=db.prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY sort_order,id').all(id);p.fitments=db.prepare('SELECT * FROM fitments WHERE product_id=? ORDER BY car_brand,model,year_from').all(id);p.aliases=db.prepare('SELECT * FROM product_aliases WHERE product_id=? ORDER BY id').all(id);return json(res,p)}
 if(u.pathname==='/api/brands'&&method==='GET')return json(res,db.prepare('SELECT b.*,count(p.id) product_count FROM brands b LEFT JOIN products p ON p.brand_id=b.id GROUP BY b.id ORDER BY b.name').all());
 if(u.pathname==='/api/categories'&&method==='GET')return json(res,db.prepare('SELECT c.*,(SELECT count(*) FROM products p WHERE p.category=c.name) product_count FROM categories c ORDER BY sort_order,name').all());
 if(u.pathname==='/api/fitment/options'&&method==='GET'){const makes=db.prepare("SELECT DISTINCT car_brand v FROM fitments WHERE car_brand<>'' ORDER BY car_brand").all().map(x=>x.v);return json(res,{makes})}
 if(u.pathname==='/api/fitment/check'&&method==='GET'){const pid=+u.searchParams.get('product_id'),make=norm(u.searchParams.get('make')),model=norm(u.searchParams.get('model')),year=+u.searchParams.get('year');const rows=db.prepare('SELECT * FROM fitments WHERE product_id=? AND lower(car_brand)=lower(?)').all(pid,make);const hit=rows.find(f=>(!model||f.model.toLowerCase().includes(model.toLowerCase())||model.toLowerCase().includes(f.model.toLowerCase()))&&(!year||(!f.year_from||year>=f.year_from)&&(!f.year_to||year<=f.year_to)));return json(res,{fits:!!hit,fitment:hit||null})}
 if(u.pathname==='/api/orders'&&method==='POST'){const d=await readJson(req);const no='TP-'+Date.now().toString().slice(-8);const r=db.prepare('INSERT INTO orders(order_no,customer_name,email,total,status) VALUES(?,?,?,?,?)').run(no,d.customer_name||'Guest',d.email||'',d.total||0,'placed');for(const x of d.items||[])db.prepare('INSERT INTO order_items(order_id,product_id,title,qty,price) VALUES(?,?,?,?,?)').run(r.lastInsertRowid,x.product_id||null,x.title,x.qty||1,x.price||0);audit('order',r.lastInsertRowid,'create',no);return json(res,{order_no:no,id:r.lastInsertRowid},201)}
 // ADMIN
 if(u.pathname==='/api/admin/stats'&&method==='GET')return json(res,{products:db.prepare('SELECT count(*) c FROM products').get().c,fitments:db.prepare('SELECT count(*) c FROM fitments').get().c,brands:db.prepare('SELECT count(*) c FROM brands').get().c,categories:db.prepare('SELECT count(*) c FROM categories').get().c,orders:db.prepare('SELECT count(*) c FROM orders').get().c,customers:db.prepare('SELECT count(*) c FROM customers').get().c,inventory:db.prepare('SELECT coalesce(sum(stock),0) c FROM products').get().c,low_stock:db.prepare('SELECT count(*) c FROM products WHERE stock<=low_stock_threshold').get().c});
 if(u.pathname==='/api/admin/products'&&method==='GET'){const q=norm(u.searchParams.get('q'));const brand=norm(u.searchParams.get('brand'));const limit=Math.min(500,Number(u.searchParams.get('limit')||100));let where=['1=1'],args=[];if(q){where.push('(p.title LIKE ? OR p.mfg_part_id LIKE ? OR p.the_plug_id LIKE ?)');args.push('%'+q+'%','%'+q+'%','%'+q+'%')}if(brand){where.push('p.brand_name=?');args.push(brand)}args.push(limit);return json(res,db.prepare(`SELECT p.*,(SELECT url FROM product_images i WHERE i.product_id=p.id ORDER BY sort_order LIMIT 1) image,(SELECT count(*) FROM fitments f WHERE f.product_id=p.id) fitment_count FROM products p WHERE ${where.join(' AND ')} ORDER BY p.updated_at DESC LIMIT ?`).all(...args))}
 if(u.pathname==='/api/admin/products'&&method==='POST'){const d=await readJson(req);const bid=getOrBrand(d.brand_name||'Unbranded');const g='manual|'+crypto.randomUUID();const r=db.prepare('INSERT INTO products(brand_id,brand_name,mfg_part_id,the_plug_id,title,short_description,description,msrp_usd,price_usd,msrp_sar,price_sar,cost_sar,category,status,stock,low_stock_threshold,lead_time,seo_title,seo_description,group_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(bid,d.brand_name||'Unbranded',d.mfg_part_id||'',d.the_plug_id||'',d.title||'Untitled product',d.short_description||'',d.description||'',d.msrp_usd||0,d.price_usd||0,d.msrp_sar||0,d.price_sar||0,d.cost_sar||0,d.category||'Other',d.status||'draft',d.stock||0,d.low_stock_threshold||3,d.lead_time||'',d.seo_title||'',d.seo_description||'',g);audit('product',r.lastInsertRowid,'create',d.title);return json(res,{id:r.lastInsertRowid},201)}
 if(u.pathname.match(/^\/api\/admin\/products\/\d+$/)&&method==='GET'){const id=+u.pathname.split('/').pop();const p=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!p)return json(res,{error:'Not found'},404);p.images=db.prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY sort_order,id').all(id);p.fitments=db.prepare('SELECT * FROM fitments WHERE product_id=? ORDER BY id').all(id);p.aliases=db.prepare('SELECT * FROM product_aliases WHERE product_id=? ORDER BY id').all(id);return json(res,p)}
 if(u.pathname.match(/^\/api\/admin\/products\/\d+$/)&&method==='PUT'){const id=+u.pathname.split('/').pop(),d=await readJson(req);const cur=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!cur)return json(res,{error:'Not found'},404);const brand=d.brand_name??cur.brand_name,bid=getOrBrand(brand);db.prepare(`UPDATE products SET brand_id=?,brand_name=?,mfg_part_id=?,the_plug_id=?,title=?,short_description=?,description=?,msrp_usd=?,price_usd=?,msrp_sar=?,price_sar=?,cost_sar=?,category=?,status=?,stock=?,low_stock_threshold=?,lead_time=?,seo_title=?,seo_description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(bid,brand,d.mfg_part_id??cur.mfg_part_id,d.the_plug_id??cur.the_plug_id,d.title??cur.title,d.short_description??cur.short_description,d.description??cur.description,d.msrp_usd??cur.msrp_usd,d.price_usd??cur.price_usd,d.msrp_sar??cur.msrp_sar,d.price_sar??cur.price_sar,d.cost_sar??cur.cost_sar,d.category??cur.category,d.status??cur.status,d.stock??cur.stock,d.low_stock_threshold??cur.low_stock_threshold,d.lead_time??cur.lead_time,d.seo_title??cur.seo_title,d.seo_description??cur.seo_description,id);audit('product',id,'update',d.title??cur.title);return json(res,{ok:true})}
 if(u.pathname.match(/^\/api\/admin\/products\/\d+$/)&&method==='DELETE'){const id=+u.pathname.split('/').pop();db.prepare('DELETE FROM products WHERE id=?').run(id);audit('product',id,'delete','');return json(res,{ok:true})}
 if(u.pathname.match(/^\/api\/admin\/products\/\d+\/images$/)&&method==='POST'){const id=+u.pathname.split('/')[4],d=await readJson(req);const order=db.prepare('SELECT coalesce(max(sort_order),0)+1 n FROM product_images WHERE product_id=?').get(id).n;const r=db.prepare('INSERT INTO product_images(product_id,url,alt_text,sort_order) VALUES(?,?,?,?)').run(id,d.url||'',d.alt_text||'',d.sort_order||order);return json(res,{id:r.lastInsertRowid},201)}
 if(u.pathname.match(/^\/api\/admin\/images\/\d+$/)&&method==='DELETE'){db.prepare('DELETE FROM product_images WHERE id=?').run(+u.pathname.split('/').pop());return json(res,{ok:true})}
 if(u.pathname.match(/^\/api\/admin\/products\/\d+\/fitments$/)&&method==='POST'){const id=+u.pathname.split('/')[4],d=await readJson(req);const [yf,yt]=years(d.year_raw||`${d.year_from||''}-${d.year_to||''}`);const r=db.prepare('INSERT INTO fitments(product_id,car_brand,model,year_from,year_to,year_raw,chassis,liters,cylinders,engine,trim,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,canonicalBrand(d.car_brand),norm(d.model),d.year_from??yf,d.year_to??yt,d.year_raw||'',d.chassis||'',d.liters||'',d.cylinders||'',d.engine||'',d.trim||'',d.notes||'');return json(res,{id:r.lastInsertRowid},201)}
 if(u.pathname.match(/^\/api\/admin\/fitments\/\d+$/)&&method==='DELETE'){db.prepare('DELETE FROM fitments WHERE id=?').run(+u.pathname.split('/').pop());return json(res,{ok:true})}
 if(u.pathname==='/api/admin/fitments'&&method==='GET'){const rows=db.prepare('SELECT f.*,p.title product_title,p.the_plug_id FROM fitments f JOIN products p ON p.id=f.product_id ORDER BY f.id DESC LIMIT 1000').all();return json(res,rows)}
 if(u.pathname==='/api/admin/brands'&&method==='GET')return json(res,db.prepare('SELECT b.*,(SELECT count(*) FROM products p WHERE p.brand_id=b.id) product_count FROM brands b ORDER BY b.name').all());
 if(u.pathname==='/api/admin/brands'&&method==='POST'){const d=await readJson(req);const r=db.prepare('INSERT INTO brands(name,slug,logo_url,website,notes) VALUES(?,?,?,?,?)').run(d.name,slug(d.name),d.logo_url||'',d.website||'',d.notes||'');return json(res,{id:r.lastInsertRowid},201)}
 if(u.pathname==='/api/admin/categories'&&method==='GET')return json(res,db.prepare('SELECT c.*,(SELECT count(*) FROM products p WHERE p.category=c.name) product_count FROM categories c ORDER BY sort_order,name').all());
 if(u.pathname==='/api/admin/categories'&&method==='POST'){const d=await readJson(req);const r=db.prepare('INSERT INTO categories(name,slug,parent_id,sort_order) VALUES(?,?,?,?)').run(d.name,slug(d.name),d.parent_id||null,d.sort_order||0);return json(res,{id:r.lastInsertRowid},201)}
 if(u.pathname==='/api/admin/orders'&&method==='GET')return json(res,db.prepare('SELECT * FROM orders ORDER BY id DESC LIMIT 200').all());
 if(u.pathname.match(/^\/api\/admin\/orders\/\d+$/)&&method==='PUT'){const id=+u.pathname.split('/').pop(),d=await readJson(req);db.prepare('UPDATE orders SET status=? WHERE id=?').run(d.status||'processing',id);audit('order',id,'status',d.status||'processing');return json(res,{ok:true})}
 if(u.pathname==='/api/admin/inventory'&&method==='GET')return json(res,db.prepare('SELECT id,the_plug_id,title,brand_name,stock,low_stock_threshold,lead_time FROM products ORDER BY stock ASC,title LIMIT 500').all());
 if(u.pathname.match(/^\/api\/admin\/inventory\/\d+$/)&&method==='POST'){const id=+u.pathname.split('/').pop(),d=await readJson(req);const delta=Number(d.delta||0);db.prepare('UPDATE products SET stock=stock+?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(delta,id);db.prepare('INSERT INTO inventory_logs(product_id,delta,reason,note) VALUES(?,?,?,?)').run(id,delta,d.reason||'manual',d.note||'');return json(res,{ok:true})}
 if(u.pathname==='/api/admin/settings'&&method==='GET'){const rows=db.prepare('SELECT key,value FROM settings').all();return json(res,Object.fromEntries(rows.map(x=>[x.key,x.value])))}
 if(u.pathname==='/api/admin/settings'&&method==='PUT'){const d=await readJson(req);for(const [k,v] of Object.entries(d))db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));return json(res,{ok:true})}
 if(u.pathname==='/api/admin/imports'&&method==='GET')return json(res,db.prepare('SELECT * FROM imports ORDER BY id DESC LIMIT 50').all());
 if(u.pathname==='/api/admin/import/preview'&&method==='POST'){const mp=parseMultipart(await body(req),req.headers['content-type']||'');if(!mp)return json(res,{error:'Upload an .xlsx file'},400);const fn=Date.now()+'-'+mp.name.replace(/[^\w. -]/g,'_');const fp=path.join(UPLOADS,fn);fs.writeFileSync(fp,mp.data);const rows=parseXlsx(fp);const keys=new Set(),issues=[],newKeys=new Set(),existingKeys=new Set(),priceChanges=[];let valid=0;for(const r of rows){if(!norm(r['Product Name'])||!norm(r['Brand']||r.__sheet)){issues.push({sheet:r.__sheet,row:r.__row,message:'Missing product name or brand'});continue}valid++;const g=groupKey(r);keys.add(g);const cur=db.prepare('SELECT id,price_sar,title FROM products WHERE group_key=?').get(g);if(cur){existingKeys.add(g);const np=money(r['The Pluge Price SAR']||r['The Plug Price SAR']);if(np!=null&&cur.price_sar!=null&&Math.abs(np-cur.price_sar)>.009)priceChanges.push({product:cur.title,old:cur.price_sar,new:np})}else newKeys.add(g)}return json(res,{token:fn,filename:mp.name,rows:rows.length,valid_rows:valid,estimated_unique_products:keys.size,new_products:newKeys.size,existing_products:existingKeys.size,price_changes:priceChanges.slice(0,100),sheets:[...new Set(rows.map(r=>r.__sheet))],issues:issues.slice(0,100),sample:rows.slice(0,5)})}
 if(u.pathname==='/api/admin/import/commit'&&method==='POST'){const d=await readJson(req);const fp=path.join(UPLOADS,path.basename(d.token||''));if(!fs.existsSync(fp))return json(res,{error:'Upload token expired'},400);const rows=parseXlsx(fp);const st=importRows(rows,d.mode||'update');db.prepare('INSERT INTO imports(filename,mode,rows_total,products_created,products_updated,fitments_created,issues,status) VALUES(?,?,?,?,?,?,?,?)').run(path.basename(fp),d.mode||'update',st.rows_total,st.products_created,st.products_updated,st.fitments_created,st.issues,'completed');return json(res,st)}
 if(u.pathname==='/api/admin/audit'&&method==='GET')return json(res,db.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT 100').all());
 return false;
}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')){const handled=await api(req,res,u);if(handled!==false)return;return json(res,{error:'API route not found'},404)}if(u.pathname==='/admin'||u.pathname==='/admin/')return staticFile(res,path.join(PUBLIC,'admin.html'));if(u.pathname==='/'||u.pathname==='/shop'||u.pathname.startsWith('/product'))return staticFile(res,path.join(PUBLIC,'index.html'));const f=path.join(PUBLIC,path.normalize(u.pathname).replace(/^(\.\.[\/\\])+/,''));if(staticFile(res,f))return;res.writeHead(404);res.end('Not found')}catch(e){console.error(e);json(res,{error:e.message},500)}});
if(process.argv.includes('--import-sample')){const src='/mnt/data/The Plug update30-6-2026.xlsx'; if(fs.existsSync(src)){const rows=parseXlsx(src);console.log(importRows(rows,'update'));}else console.log('Sample workbook not found');process.exit(0)}
const PORT=process.env.PORT||4173;server.listen(PORT,()=>console.log(`The Plug AI full stack v0.6 running at http://localhost:${PORT}  Admin: http://localhost:${PORT}/admin`));
